# Generated by Django 5.1.3 on 2024-11-20 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='user',
            new_name='username',
        ),
    ]
