# Generated by Django 5.1.3 on 2024-11-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='book',
            field=models.ManyToManyField(help_text='Book model', related_name='books', to='books.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Genre', related_name='genres', to='books.genre'),
        ),
    ]
