# Generated by Django 5.1.3 on 2024-11-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_genre_book_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Genre', related_name='genre_list', to='books.genre'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='book',
            field=models.ManyToManyField(help_text='Book model', related_name='books_list', to='books.book'),
        ),
    ]
