# Generated by Django 5.1.3 on 2024-11-14 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_genre_alter_genre_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='book',
        ),
    ]
