# Generated by Django 5.1.3 on 2024-11-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_alter_book_author_alter_book_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='book',
        ),
        migrations.AddField(
            model_name='rent',
            name='book',
            field=models.ManyToManyField(help_text='rent book', related_name='books_list', to='books.book'),
        ),
    ]
