# Generated by Django 5.1.3 on 2024-11-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_remove_rent_book_rent_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='transaction_date_created',
            field=models.DateTimeField(auto_now_add=True, help_text='Date of transaction'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='transaction_date_update',
            field=models.DateTimeField(auto_now=True, help_text='Date of last update transaction'),
        ),
    ]
