# Generated by Django 5.1.3 on 2024-11-16 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_rent_transaction_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='deadline',
        ),
    ]
