# Generated by Django 5.1.3 on 2024-11-16 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_remove_rent_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='tax_amount',
        ),
    ]
