# Generated by Django 5.1.3 on 2024-11-16 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_remove_rent_tax_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='user',
        ),
    ]
