# Generated by Django 5.1.3 on 2024-11-16 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_rent_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='deadline',
            field=models.DateField(blank=True, help_text='The deadline date of rent book, red flag!', null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='tax_amount',
            field=models.FloatField(blank=True, help_text='Total tax amount for revenue', null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='debtor user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
