# Generated by Django 5.1.3 on 2024-11-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_rent_deadline_rent_tax_amount_alter_rent_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='The deadline date of rent book, red flag!', null=True),
        ),
    ]
