# Generated by Django 5.1.3 on 2024-11-16 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_alter_rent_deadline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='book',
            new_name='books',
        ),
    ]
