# Generated by Django 5.1.3 on 2024-11-16 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0016_rename_book_rent_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='transaction_date_created',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='transaction_date_update',
            new_name='record_updated',
        ),
    ]
