# Generated by Django 5.1.3 on 2024-11-16 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_rename_transaction_date_created_rent_published_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='deadline',
            field=models.DateTimeField(help_text='The deadline date of rent book, red flag!'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='tax_amount',
            field=models.FloatField(help_text='Total tax amount for revenue'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(help_text='debtor user', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
