# Generated by Django 5.1.3 on 2024-11-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0018_alter_rent_deadline_alter_rent_tax_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='books',
            new_name='book',
        ),
    ]
