# Generated by Django 5.1.3 on 2024-11-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0019_rename_books_rent_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='book',
            new_name='books',
        ),
    ]
