# Generated by Django 5.1.3 on 2024-11-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0020_rename_book_rent_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Shows if book is available for rent'),
        ),
    ]
