# Generated by Django 5.1.3 on 2024-11-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0021_book_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('pk',), 'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
